[SELC-5272] feat: Field validation Unique code or SDI
pagopa/selfcare-onboarding-frontend pull request #1018
Opened 2024-07-18 17:03 UTC by GabrieleMaiocchiFilippo

#### List of Changes

[SELC-5272] feat: Field validation Unique code or SDI

#### Motivation and Context

Allows to insert in the textfield only: seven characters, uppercase letters, alphanumeric characters

#### How Has This Been Tested?

Checked the insertion of characters for the SDI input field

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-07-19 09:27 UTC, loremedda commented
The implementation is correct, even the unit test re-adaptation. You should just test the new feature introduced

2024-07-19 09:27 UTC, loremedda requested changes
The implementation is correct, even the unit test re-adaptation. You should just test the new feature introduced

2024-07-19 16:00 UTC, loremedda commented
OK

2024-07-22 09:59 UTC, andrea-putzu approved these changes

2024-07-22 10:03 UTC, loremedda approved these changes

2024-07-22 10:19 UTC, merged