[SELC-5314] feat: SFE Billing Code field validation
pagopa/selfcare-onboarding-frontend pull request #1030
Opened 2024-07-24 16:32 UTC by GabrieleMaiocchiFilippo

#### List of Changes

[SELC-5314] feat: SFE Billing Code field validation

#### Motivation and Context

the field for sfe has to be free and be validated calling the API verifyTaxCodeInvoicing

#### How Has This Been Tested?

Tested if when landing in page the field SFE is free and editable.
Tested if at the change of the value SFE field the API verifyTaxCodeInvoicing has been called with the correct values and that has been retrived the correct response.

#### Screenshots (if appropriate):

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-07-25 10:03 UTC, loremedda requested changes

2024-07-25 10:03 UTC, loremedda commented on src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx
> +  taxCodeInvoicing: 'AAAAAA44D55F456K',
? if i check in the mocks, this taxCode is not present

2024-07-25 10:03 UTC, loremedda commented on src/views/onboardingProduct/__tests__/OnboardingProduct.test.tsx
> +    fireEvent.change(taxCodeInvoicing, { target: { value: 'AAAAAA44D55F456K' } });
? if i check in the mocks, this taxCode is not present

2024-07-25 10:07 UTC, loremedda requested changes
Unit tests must ensure that a functionality that has been tested with a behavior test that satisfies the business requirement..
From your code I see that the call is invoked when the 11th character is reached, here you would be inserting 16 characters
The user can potentially enter up to 100 characters as you have not set a length limit on the textfield

2024-07-25 10:09 UTC, loremedda requested changes
Add a positive use case in the mocks and test that when it is inserted, the validation is successful, otherwise the error we expect. Make sure the feature works locally first, then testing

2024-07-25 16:35 UTC, loremedda approved these changes

2024-07-29 07:47 UTC, gianmarcoplutino approved these changes

2024-07-29 07:53 UTC, merged